name: general

on:
  push:
    paths:
      - 'pages/*'

jobs:

  update:
    runs-on: ubuntu-latest
    container:
      image: gabrielbdornas/livemark:latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean Html Pages
        run: make clean
      - name: Build Livemark
        run: make build
      - name: Commit new datapackage.json
        uses: stefanzweifel/git-auto-commit-action@v4 
